### ISSUE TITLE
v4: fetch object by id not working

### ISSUE THREAD

**Issue by SavvasMohito** [weaviate/weaviate-python-client#706]
Hi there, I have been using the v4 client on version 4.4b6 along with the latest server version 1.23.1. I noticed that `collection.query.fetch_object_by_id(uuid)` is not working. It probably has to do with the new functions added for v1.23 [here](https://github.com/weaviate/weaviate-python-client/blob/bd215a950dda619988b0e25a6ca56110241331a0/weaviate/collections/queries/fetch_object_by_id.py#L146), because the HTTP endpoint is working correctly. There is no error coming back when performing the function, it just doesn't return something back.

**Comment by tsmith023** [comment]
What is the specific error that you are seeing when you use the method?

**Comment by SavvasMohito** [comment]
I am not seeing any error, I just get an empty result. I know for a fact that the ID I am trying to fetch exists, I can normally retrieve it using the HTTP API.

**Comment by tsmith023** [comment]
There's a decently large amount of use of `fetch_object_by_id` in our integration tests for the v4 client! Would you be able to post a Minimum Reproducible Example (MRE) of your client/collection/Weaviate configuration that replicates the issue that you're seeing?

**Comment by SavvasMohito** [comment]
I just tested out creating a dummy collection, adding an object to it and then using `fetch_object_by_id` which worked correctly. The issue still occurs when trying to `fetch_object_by_id` from my existing collections though, which were created with older versions of the client and Weaviate.

My weaviate configuration
```yaml
version: '3.9'

services:
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
      - --read-timeout=300s
      - --write-timeout=300s
    image: semitechnologies/weaviate:1.23.1
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - /home/ubuntu/weaviate/var/weaviate:/var/lib/weaviate
      - /home/ubuntu/weaviate/backups:/var/lib/backups
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'  
      BACKUP_FILESYSTEM_PATH: '/var/lib/backups'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: text2vec-openai, backup-filesystem
      CLUSTER_HOSTNAME: 'node1'
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      LIMIT_RESOURCES: true
```

client configuration
```python
import weaviate
client = weaviate.connect_to_local(host="10.68.XXX.XX")
collection = client.collections.get("debug")
collection.query.fetch_object_by_id('dc93bf76-0a22-47b4-81c4-6e153d815e9f')
```

collection setup
```python
weaviate_client.collections.create(
        name="debug",
        description="",
        vectorizer_config=wvc.Configure.Vectorizer.text2vec_openai(),
        properties=[
            wvc.Property(name="description", data_type=wvc.DataType.TEXT),
            wvc.Property(name="outcomeid", data_type=wvc.DataType.TEXT, skip_vectorization=True),
            wvc.Property(name="companyName", data_type=wvc.DataType.TEXT, skip_vectorization=True),
            # Optional
            wvc.Property(name="url", data_type=wvc.DataType.TEXT, skip_vectorization=True),
            wvc.Property(name="impact", data_type=wvc.DataType.TEXT),
            wvc.Property(name="website", data_type=wvc.DataType.TEXT, skip_vectorization=True),
            wvc.Property(name="yearEstablished", data_type=wvc.DataType.TEXT, skip_vectorization=True)
        ],
    )
```
